# This rule is not used by the project galaxy itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to astronomy.galaxy.kubesphere.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: galaxy
    app.kubernetes.io/managed-by: kustomize
  name: galaxy-viewer-role
rules:
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies/status
  verbs:
  - get
