# This rule is not used by the project galaxy itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the astronomy.galaxy.kubesphere.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: galaxy
    app.kubernetes.io/managed-by: kustomize
  name: galaxy-editor-role
rules:
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies/status
  verbs:
  - get
