---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies
  - planets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies/finalizers
  - planets/finalizers
  verbs:
  - update
- apiGroups:
  - astronomy.galaxy.kubesphere.io
  resources:
  - galaxies/status
  - planets/status
  verbs:
  - get
  - patch
  - update
